In [1]:
import torch

Scalar

In [3]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

Vector

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

Matrix

In [9]:
MATRIX = torch.tensor([[7,8],[9,10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

Tensor

In [12]:
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])

In [13]:
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

Random Tensors

In [16]:
random_tensor = torch.rand(size = (224,224,3))

In [17]:
random_tensor

tensor([[[0.9717, 0.5149, 0.5533],
         [0.6724, 0.1029, 0.0480],
         [0.9502, 0.1223, 0.8966],
         ...,
         [0.2930, 0.3353, 0.5796],
         [0.4309, 0.4007, 0.0779],
         [0.0333, 0.9126, 0.4621]],

        [[0.0129, 0.0471, 0.3490],
         [0.1541, 0.8127, 0.6435],
         [0.8643, 0.3152, 0.7318],
         ...,
         [0.7772, 0.5362, 0.7310],
         [0.8624, 0.7020, 0.6688],
         [0.9303, 0.0938, 0.0366]],

        [[0.5699, 0.6675, 0.7129],
         [0.7345, 0.6093, 0.8845],
         [0.6112, 0.9968, 0.0601],
         ...,
         [0.4490, 0.5456, 0.2259],
         [0.3141, 0.3747, 0.8873],
         [0.7425, 0.0854, 0.3678]],

        ...,

        [[0.3090, 0.6548, 0.1516],
         [0.3385, 0.1219, 0.5978],
         [0.3077, 0.5426, 0.7802],
         ...,
         [0.2910, 0.1062, 0.6061],
         [0.5203, 0.7390, 0.3446],
         [0.1722, 0.0107, 0.2915]],

        [[0.5048, 0.0162, 0.6525],
         [0.1003, 0.4368, 0.1457],
         [0.

Zeros and Ones

In [18]:
zeros =torch.zeros(size=(3,4))

In [19]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size=(3,4))

In [21]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Range

In [22]:
torch_range = torch.arange(start=1,end=10,step=1)

In [23]:
torch_range

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
test = torch.zeros_like(input=torch_range)

In [25]:
test

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
float_16_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float16)

In [27]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

Find info

In [28]:
som_tensor = torch.rand(3,4)

In [29]:
print(som_tensor)

tensor([[0.8832, 0.8376, 0.8489, 0.1102],
        [0.3315, 0.9096, 0.8865, 0.5169],
        [0.9308, 0.0984, 0.8555, 0.3900]])


In [30]:
print(som_tensor.shape)

torch.Size([3, 4])


In [31]:
print(som_tensor.dtype)

torch.float32


In [32]:
som_tensor.device

device(type='cpu')

Basic Operations

In [33]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [34]:
tensor *10

tensor([10, 20, 30])

In [35]:
tensor = tensor - 10

In [36]:
tensor

tensor([-9, -8, -7])

In [37]:
tensor = tensor + 10

In [38]:
tensor

tensor([1, 2, 3])

In [39]:
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [40]:
tensor

tensor([1, 2, 3])

In [41]:
tensor *tensor

tensor([1, 4, 9])

Matrix Multiplication

In [42]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [43]:
tensor *tensor

tensor([1, 4, 9])

In [44]:
torch.matmul(tensor,tensor)

tensor(14)

In [45]:
tensor @ tensor

tensor(14)

In [46]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

In [47]:
print(tensor_A)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [48]:
print(tensor_B.T)

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [49]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [50]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [51]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features = 3, out_features=6)

x=tensor_A.T
output = linear(x)
x.shape
output.shape

torch.Size([2, 6])


Finding the min, max, mean, sum, etc (aggregation)

In [52]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [54]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

Positional min/max

In [55]:
#Index where max and min values occur
tensor = torch.arange(10,100,10)

In [56]:
tensor

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
tensor.argmax()

tensor(8)

In [58]:
tensor.argmin()

tensor(0)

Change tensor datatype

In [59]:
tensor = torch.arange(10,100,10)
tensor.dtype

torch.int64

In [60]:
tensor.type(torch.float16)

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [61]:
tensor.type(torch.int8)

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

Squeezing and Reshaping

In [62]:
import torch
x = torch.arange(1., 8.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [63]:
#Add an extra dimension
x_reshaped = x.reshape(1,7)

In [64]:
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [65]:
z = x.view

In [66]:
z

<function Tensor.view>

In [68]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [69]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [70]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [71]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
1.0


IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

Numpy

In [72]:
import torch
import numpy as np
array = np.arange(1.,8.)
tensor = torch.from_numpy(array)

In [73]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [74]:
array

array([1., 2., 3., 4., 5., 6., 7.])

In [75]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducability

In [77]:
import torch
import random

# # Set the random seed
RANDOM_SEED=24 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.7644, 0.3751, 0.0751, 0.5308],
        [0.9660, 0.2770, 0.3372, 0.8910],
        [0.4304, 0.3090, 0.3993, 0.5183]])

Tensor D:
tensor([[0.7644, 0.3751, 0.0751, 0.5308],
        [0.9660, 0.2770, 0.3372, 0.8910],
        [0.4304, 0.3090, 0.3993, 0.5183]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [78]:
!nvidia-smi

Thu Aug  1 20:14:02 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.26                 Driver Version: 546.26       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce MX450         WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   53C    P0              N/A / ERR! |      0MiB /  2048MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [79]:
torch.cuda.is_available()

True

In [80]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [81]:
# Count number of devices
torch.cuda.device_count()

1

In [82]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

Exercises

In [2]:
import torch

In [5]:
random = torch.rand(size=(7,7))

In [6]:
random

tensor([[0.7967, 0.5593, 0.8726, 0.2787, 0.2955, 0.1496, 0.2627],
        [0.6975, 0.5026, 0.2137, 0.1231, 0.9696, 0.7768, 0.6408],
        [0.8900, 0.9164, 0.8651, 0.0210, 0.7918, 0.4770, 0.0308],
        [0.6009, 0.7934, 0.1619, 0.9641, 0.2631, 0.2267, 0.6214],
        [0.1784, 0.7689, 0.6176, 0.0794, 0.0868, 0.1443, 0.7508],
        [0.0287, 0.4114, 0.4460, 0.3045, 0.8152, 0.1228, 0.6772],
        [0.8331, 0.0450, 0.0143, 0.0800, 0.6663, 0.6900, 0.9597]])

In [7]:
random2 = torch.rand(size=(1,7))

In [9]:
random2

tensor([[0.1022, 0.9344, 0.2140, 0.3968, 0.0167, 0.4195, 0.8394]])

In [14]:
trandom2 = random2.T

In [15]:
trandom2

tensor([[0.1022],
        [0.9344],
        [0.2140],
        [0.3968],
        [0.0167],
        [0.4195],
        [0.8394]])

In [17]:
multip = random.matmul(trandom2)

In [18]:
multip

tensor([[1.1896],
        [1.5154],
        [1.3799],
        [1.8412],
        [1.5926],
        [1.2373],
        [1.2682]])

In [19]:
random_seed = 0 
torch.manual_seed(seed=random_seed)

In [20]:
random = torch.rand(size=(7,7))

In [21]:
random

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [22]:
random2 = torch.rand(size=(1,7))
trandom2 = random2.T

In [23]:
multip = random.matmul(trandom2)

In [24]:
multip

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [26]:
torch.cuda.manual_seed(seed=1234)

In [27]:
rand1 = torch.rand(size=(2,3))
rand2 = torch.rand(size=(2,3))

In [29]:
rand2

tensor([[0.2038, 0.6511, 0.7745],
        [0.4369, 0.5191, 0.6159]])

In [30]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [31]:
rand1.to(device)

tensor([[0.5932, 0.1123, 0.1535],
        [0.2417, 0.7262, 0.7011]], device='cuda:0')

In [32]:
rand2.to(device)

tensor([[0.2038, 0.6511, 0.7745],
        [0.4369, 0.5191, 0.6159]], device='cuda:0')

In [34]:
op = torch.matmul(rand1, rand2.T)

In [35]:
torch.max(op)

tensor(1.0651)

In [36]:
torch.min(op)

tensor(0.3129)

In [37]:
torch.argmax(op)

tensor(2)

In [38]:
torch.argmin(op)

tensor(0)

In [42]:
rand1 = torch.rand(size=(1,1,1,10))

In [43]:
rand1

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [41]:
torch.manual_seed(seed=7)

In [44]:
rand1.squeeze()

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])